apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: 264473175039.dkr.ecr.us-east-1.amazonaws.com/test:latest
        name: solar-system
        ports: 
        - containerPort: 80
